// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetServerInfoData, GetServerInfoResponse, GetServerInfoError, PingServerData, PingServerResponse, TokenGenerateData, TokenGenerateResponse2, TokenGenerateError, TokenRolesData, TokenRolesResponse2, TokenRolesError, GetAvailableModelsData, GetAvailableModelsResponse, GetAvailableModelsError, GetAvailableModelData, GetAvailableModelResponse, GetAvailableModelError, CreateModelInstanceData, CreateModelInstanceResponse2, CreateModelInstanceError, GetModelInstancesData, GetModelInstancesResponse, GetModelInstancesError, DeleteModelInstanceData, DeleteModelInstanceResponse, DeleteModelInstanceError, GetModelInstanceData, GetModelInstanceResponse, GetModelInstanceError, GetModelInstanceStateData, GetModelInstanceStateResponse, GetModelInstanceStateError, GetModelInstanceParametersData, GetModelInstanceParametersResponse, GetModelInstanceParametersError, RunInferenceData, RunInferenceResponse, RunInferenceError, RunLearningData, RunLearningResponse, RunLearningError, CreateEpisodeData, CreateEpisodeResponse, CreateEpisodeError, GetEpisodesData, GetEpisodesResponse, GetEpisodesError, DeleteEpisodeData, DeleteEpisodeResponse, DeleteEpisodeError, GetEpisodeInfoData, GetEpisodeInfoResponse, GetEpisodeInfoError, AttachEventsToEpisodeData, AttachEventsToEpisodeResponse, AttachEventsToEpisodeError, WipeEpisodeData, WipeEpisodeResponse, WipeEpisodeError, AttachMetadataToEventData, AttachMetadataToEventResponse, AttachMetadataToEventError } from './types.gen';
import { zGetServerInfoResponse, zPingServerResponse, zTokenGenerateResponse2, zTokenRolesResponse2, zGetAvailableModelsResponse, zGetAvailableModelResponse, zCreateModelInstanceResponse2, zGetModelInstancesResponse, zDeleteModelInstanceResponse, zGetModelInstanceResponse, zGetModelInstanceStateResponse, zGetModelInstanceParametersResponse, zRunInferenceResponse, zRunLearningResponse, zCreateEpisodeResponse, zGetEpisodesResponse, zDeleteEpisodeResponse, zGetEpisodeInfoResponse, zAttachEventsToEpisodeResponse, zWipeEpisodeResponse, zAttachMetadataToEventResponse } from './zod.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get server information
 * Returns information about the server, such as the RxInferServer version, RxInfer version, Julia version, server edition and API version
 */
export const getServerInfo = <ThrowOnError extends boolean = false>(options?: Options<GetServerInfoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetServerInfoResponse, GetServerInfoError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetServerInfoResponse.parseAsync(data);
        },
        url: '/info',
        ...options
    });
};

/**
 * Health check endpoint
 * Simple endpoint to check if the server is alive and running
 */
export const pingServer = <ThrowOnError extends boolean = false>(options?: Options<PingServerData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<PingServerResponse, unknown, ThrowOnError>({
        responseValidator: async (data) => {
            return await zPingServerResponse.parseAsync(data);
        },
        url: '/ping',
        ...options
    });
};

/**
 * Generate authentication token
 * Generates a new authentication token for accessing protected endpoints
 */
export const tokenGenerate = <ThrowOnError extends boolean = false>(options?: Options<TokenGenerateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<TokenGenerateResponse2, TokenGenerateError, ThrowOnError>({
        responseValidator: async (data) => {
            return await zTokenGenerateResponse2.parseAsync(data);
        },
        url: '/token/generate',
        ...options
    });
};

/**
 * Get token roles
 * Retrieve the list of roles for a specific token
 */
export const tokenRoles = <ThrowOnError extends boolean = false>(options?: Options<TokenRolesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<TokenRolesResponse2, TokenRolesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zTokenRolesResponse2.parseAsync(data);
        },
        url: '/token/roles',
        ...options
    });
};

/**
 * Get models available for creation
 * Retrieve the list of models available for creation for a given token.
 * This list specifies names and available arguments for each model.
 *
 * **Note** The list of available models might differ for different access tokens.
 * For example, a token with only the "user" role might not have access to all models.
 *
 */
export const getAvailableModels = <ThrowOnError extends boolean = false>(options?: Options<GetAvailableModelsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAvailableModelsResponse, GetAvailableModelsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetAvailableModelsResponse.parseAsync(data);
        },
        url: '/models/available',
        ...options
    });
};

/**
 * Get information about a specific model available for creation
 * Retrieve detailed information about a specific model available for creation
 */
export const getAvailableModel = <ThrowOnError extends boolean = false>(options: Options<GetAvailableModelData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAvailableModelResponse, GetAvailableModelError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetAvailableModelResponse.parseAsync(data);
        },
        url: '/models/available/{model_name}',
        ...options
    });
};

/**
 * Create a new model instance
 * Creates a new instance of a model with the specified configuration
 */
export const createModelInstance = <ThrowOnError extends boolean = false>(options: Options<CreateModelInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateModelInstanceResponse2, CreateModelInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zCreateModelInstanceResponse2.parseAsync(data);
        },
        url: '/models/create-instance',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get all created model instances
 * Retrieve detailed information about all created model instances for a specific token
 */
export const getModelInstances = <ThrowOnError extends boolean = false>(options?: Options<GetModelInstancesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetModelInstancesResponse, GetModelInstancesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetModelInstancesResponse.parseAsync(data);
        },
        url: '/models/instances',
        ...options
    });
};

/**
 * Delete a model instance
 * Delete a specific model instance by its ID
 */
export const deleteModelInstance = <ThrowOnError extends boolean = false>(options: Options<DeleteModelInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteModelInstanceResponse, DeleteModelInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zDeleteModelInstanceResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}',
        ...options
    });
};

/**
 * Get model instance information
 * Retrieve detailed information about a specific model instance
 */
export const getModelInstance = <ThrowOnError extends boolean = false>(options: Options<GetModelInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetModelInstanceResponse, GetModelInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetModelInstanceResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}',
        ...options
    });
};

/**
 * Get the state of a model instance
 * Retrieve the state of a specific model instance
 */
export const getModelInstanceState = <ThrowOnError extends boolean = false>(options: Options<GetModelInstanceStateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetModelInstanceStateResponse, GetModelInstanceStateError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetModelInstanceStateResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/state',
        ...options
    });
};

/**
 * Get the parameters of a model instance
 * Retrieve the parameters of a specific model instance
 */
export const getModelInstanceParameters = <ThrowOnError extends boolean = false>(options: Options<GetModelInstanceParametersData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetModelInstanceParametersResponse, GetModelInstanceParametersError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetModelInstanceParametersResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/parameters',
        ...options
    });
};

/**
 * Run inference
 * Run inference on a specific model instance
 */
export const runInference = <ThrowOnError extends boolean = false>(options: Options<RunInferenceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RunInferenceResponse, RunInferenceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zRunInferenceResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/infer',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Learn from previous observations
 * Learn from previous episodes for a specific model
 */
export const runLearning = <ThrowOnError extends boolean = false>(options: Options<RunLearningData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RunLearningResponse, RunLearningError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zRunLearningResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/learn',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Create a new episode for a model instance
 * Create a new episode for a specific model instance.
 * Note that the default episode is created automatically when the model instance is created.
 * When a new episode is created, it becomes the current episode for the model instance.
 *
 */
export const createEpisode = <ThrowOnError extends boolean = false>(options: Options<CreateEpisodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateEpisodeResponse, CreateEpisodeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zCreateEpisodeResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/create-episode',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get all episodes for a model instance
 * Retrieve all episodes for a specific model instance
 */
export const getEpisodes = <ThrowOnError extends boolean = false>(options: Options<GetEpisodesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEpisodesResponse, GetEpisodesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetEpisodesResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/episodes',
        ...options
    });
};

/**
 * Delete an episode for a model
 * Delete a specific episode for a model instance.
 * Note that the default episode cannot be deleted, but you can wipe data from it.
 * If the deleted episode was the current episode, the default episode will become the current episode.
 *
 */
export const deleteEpisode = <ThrowOnError extends boolean = false>(options: Options<DeleteEpisodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteEpisodeResponse, DeleteEpisodeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zDeleteEpisodeResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/episodes/{episode_name}',
        ...options
    });
};

/**
 * Get episode information
 * Retrieve information about a specific episode of a model
 */
export const getEpisodeInfo = <ThrowOnError extends boolean = false>(options: Options<GetEpisodeInfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEpisodeInfoResponse, GetEpisodeInfoError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zGetEpisodeInfoResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/episodes/{episode_name}',
        ...options
    });
};

/**
 * Attach events to an episode
 * Attach events to a specific episode for a model
 */
export const attachEventsToEpisode = <ThrowOnError extends boolean = false>(options: Options<AttachEventsToEpisodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AttachEventsToEpisodeResponse, AttachEventsToEpisodeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zAttachEventsToEpisodeResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/episodes/{episode_name}/attach-events',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Wipe all events from an episode
 * Wipe all events from a specific episode for a model
 */
export const wipeEpisode = <ThrowOnError extends boolean = false>(options: Options<WipeEpisodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<WipeEpisodeResponse, WipeEpisodeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zWipeEpisodeResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/episodes/{episode_name}/wipe',
        ...options
    });
};

/**
 * Attach metadata to an event
 * Attach metadata to a specific event for a model
 */
export const attachMetadataToEvent = <ThrowOnError extends boolean = false>(options: Options<AttachMetadataToEventData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AttachMetadataToEventResponse, AttachMetadataToEventError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseValidator: async (data) => {
            return await zAttachMetadataToEventResponse.parseAsync(data);
        },
        url: '/models/i/{instance_id}/episodes/{episode_name}/events/{event_id}/attach-metadata',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};