// This file is auto-generated by @hey-api/openapi-ts

export type SuccessResponse = {
    /**
     * Success message
     */
    message: string;
};

export type ErrorResponse = {
    /**
     * Error message explaining the failure
     */
    error: string;
    /**
     * Additional message providing details about the failure
     */
    message?: string;
};

export type NotFoundResponse = {
    /**
     * Error type, always "Not Found" for this error
     */
    error: 'Not Found';
    /**
     * Detailed message explaining why the resource was not found
     */
    message: string;
};

export type UnauthorizedResponse = {
    /**
     * Error type, always "Unauthorized" for this error
     */
    error: 'Unauthorized';
    /**
     * Detailed message explaining why authentication failed
     */
    message: string;
};

export type PingResponse = {
    /**
     * Status of the server
     */
    status: string;
};

export type ServerInfo = {
    /**
     * The version of RxInfer that the server is using, returns unknown if the version is unknown or hidden
     */
    rxinfer_version: string;
    /**
     * The version of the RxInferServer, returns unknown if the version is unknown or hidden
     */
    server_version: string;
    /**
     * The edition of the RxInferServer, as set in RXINFER_EDITION environment variable
     */
    server_edition: string;
    /**
     * The version of Julia as presented in VERSION
     */
    julia_version: string;
    /**
     * The version of the API being used
     */
    api_version: string;
};

export type TokenGenerateResponse = {
    /**
     * The token to use in the Authorization header with the format "Bearer {token}"
     */
    token: string;
};

export type TokenRolesResponse = {
    /**
     * List of roles for the token
     */
    roles: Array<string>;
};

export type AvailableModel = {
    /**
     * Primary model details. Note that these are also included in the `config` object.
     *
     */
    details: {
        /**
         * Name of the model (usually with the version identifier, e.g. "BetaBernoulli-v1")
         */
        name?: string;
        /**
         * Brief description of the model
         */
        description?: string;
        /**
         * Author of the model
         */
        author?: string;
        /**
         * List of roles that can access the model
         */
        roles?: Array<string>;
    };
    /**
     * The entire model configuration as in the `config.yaml` file.
     * May include arbitrary fields, which are not part of the public interface.
     * Note that this information also includes the properties from the `details` object.
     *
     */
    config: {
        [key: string]: unknown;
    };
};

export type CreateModelInstanceRequest = {
    /**
     * The name of the model to create (including version identifier if applicable, e.g. "BetaBernoulli-v1")
     */
    model_name: string;
    /**
     * Model-specific configuration arguments
     */
    arguments?: {
        [key: string]: unknown;
    };
    /**
     * Optional description of the model instance
     */
    description?: string;
};

export type CreateModelInstanceResponse = {
    /**
     * Unique identifier for the created model instance
     */
    instance_id: string;
};

export type ModelInstance = {
    /**
     * Unique identifier for the created model instance
     */
    instance_id: string;
    /**
     * Name of the model (including version identifier if applicable, e.g. "BetaBernoulli-v1")
     */
    model_name: string;
    /**
     * Timestamp of when the model was created
     */
    created_at: string;
    /**
     * Description of the created model instance
     */
    description: string;
    /**
     * Model-specific configuration arguments
     */
    arguments: {
        [key: string]: unknown;
    };
    /**
     * Name of the current episode for this model
     */
    current_episode: string;
};

export type DeleteModelInstanceRequest = {
    /**
     * ID of the model instance to delete
     */
    instance_id: string;
};

export type ModelInstanceState = {
    /**
     * An object containing the current state of the model instance.
     * May include arbitrary fields specific to the model. See the model documentation for more details.
     *
     */
    state: {
        [key: string]: unknown;
    };
};

export type ModelInstanceParameters = {
    /**
     * An object containing the current parameters of the model instance.
     * The keys are the parameter names as defined in the model configuration, and the values are the parameter values.
     *
     */
    parameters: {
        [key: string]: unknown;
    };
};

export type InferRequest = {
    /**
     * Model-specific data to run inference on
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Timestamp of the inference request, used to mark the event in the episode
     */
    timestamp?: string;
    /**
     * Name of the episode to run inference on
     */
    episode_name?: string;
};

export type InferResponse = {
    /**
     * Unique identifier for the inference event
     */
    event_id: number;
    /**
     * Model-specific results of the inference
     */
    results: {
        [key: string]: unknown;
    };
    /**
     * List of errors that occurred during the inference call, but were not fatal and the inference was still completed successfully
     */
    errors: Array<ErrorResponse>;
};

export type LearnRequest = {
    /**
     * List of episodes to learn from
     */
    episodes: Array<string>;
};

export type LearnResponse = {
    /**
     * A dictionary of learned parameters and their values
     */
    learned_parameters: {
        [key: string]: unknown;
    };
};

export type CreateEpisodeRequest = {
    /**
     * Name of the episode to create
     */
    name: string;
};

export type EpisodeInfo = {
    /**
     * ID of the model instance this episode belongs to
     */
    instance_id: string;
    /**
     * Name of the episode
     */
    episode_name: string;
    /**
     * Timestamp of when the episode was created
     */
    created_at: string;
    /**
     * List of events that have occurred in the episode
     */
    events: Array<{
        [key: string]: unknown;
    }>;
};

export type AttachEventsToEpisodeRequest = {
    /**
     * List of events to attach to the episode
     */
    events: Array<{
        /**
         * Timestamp of the event
         */
        timestamp?: string;
        /**
         * Arbitrary data to attach to the event, model-specific
         */
        data?: {
            [key: string]: unknown;
        };
        /**
         * Arbitrary metadata to attach to the event, model-specific
         */
        metadata?: {
            [key: string]: unknown;
        };
    }>;
};

export type AttachMetadataToEventRequest = {
    /**
     * Metadata to attach to the event
     */
    metadata: {
        [key: string]: unknown;
    };
};

export type GetServerInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/info';
};

export type GetServerInfoErrors = {
    /**
     * Access token is missing or invalid
     */
    401: UnauthorizedResponse;
};

export type GetServerInfoError = GetServerInfoErrors[keyof GetServerInfoErrors];

export type GetServerInfoResponses = {
    /**
     * Successfully retrieved server information
     */
    200: ServerInfo;
};

export type GetServerInfoResponse = GetServerInfoResponses[keyof GetServerInfoResponses];

export type PingServerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type PingServerResponses = {
    /**
     * Successfully pinged the server
     */
    200: PingResponse;
};

export type PingServerResponse = PingServerResponses[keyof PingServerResponses];

export type TokenGenerateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/token/generate';
};

export type TokenGenerateErrors = {
    /**
     * Unable to generate token
     */
    400: ErrorResponse;
};

export type TokenGenerateError = TokenGenerateErrors[keyof TokenGenerateErrors];

export type TokenGenerateResponses = {
    /**
     * Successfully generated authentication token
     */
    200: TokenGenerateResponse;
};

export type TokenGenerateResponse2 = TokenGenerateResponses[keyof TokenGenerateResponses];

export type TokenRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/token/roles';
};

export type TokenRolesErrors = {
    /**
     * Access token is missing or invalid
     */
    401: UnauthorizedResponse;
};

export type TokenRolesError = TokenRolesErrors[keyof TokenRolesErrors];

export type TokenRolesResponses = {
    /**
     * Successfully retrieved token roles
     */
    200: TokenRolesResponse;
};

export type TokenRolesResponse2 = TokenRolesResponses[keyof TokenRolesResponses];

export type GetAvailableModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models/available';
};

export type GetAvailableModelsErrors = {
    /**
     * Access token is missing or invalid
     */
    401: UnauthorizedResponse;
};

export type GetAvailableModelsError = GetAvailableModelsErrors[keyof GetAvailableModelsErrors];

export type GetAvailableModelsResponses = {
    /**
     * Successfully retrieved list of models available for creation
     */
    200: Array<AvailableModel>;
};

export type GetAvailableModelsResponse = GetAvailableModelsResponses[keyof GetAvailableModelsResponses];

export type GetAvailableModelData = {
    body?: never;
    path: {
        /**
         * Name of the model to retrieve information for (including version identifier if applicable, e.g. "BetaBernoulli-v1")
         */
        model_name: string;
    };
    query?: never;
    url: '/models/available/{model_name}';
};

export type GetAvailableModelErrors = {
    /**
     * Access token is missing or invalid
     */
    401: UnauthorizedResponse;
    /**
     * Model cannot be found
     */
    404: NotFoundResponse;
};

export type GetAvailableModelError = GetAvailableModelErrors[keyof GetAvailableModelErrors];

export type GetAvailableModelResponses = {
    /**
     * Successfully retrieved model details
     */
    200: AvailableModel;
};

export type GetAvailableModelResponse = GetAvailableModelResponses[keyof GetAvailableModelResponses];

export type CreateModelInstanceData = {
    body: CreateModelInstanceRequest;
    path?: never;
    query?: never;
    url: '/models/create-instance';
};

export type CreateModelInstanceErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Access token is missing or invalid
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type CreateModelInstanceError = CreateModelInstanceErrors[keyof CreateModelInstanceErrors];

export type CreateModelInstanceResponses = {
    /**
     * Model instance created successfully
     */
    200: CreateModelInstanceResponse;
};

export type CreateModelInstanceResponse2 = CreateModelInstanceResponses[keyof CreateModelInstanceResponses];

export type GetModelInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models/instances';
};

export type GetModelInstancesErrors = {
    /**
     * Access token is missing or invalid
     */
    401: UnauthorizedResponse;
};

export type GetModelInstancesError = GetModelInstancesErrors[keyof GetModelInstancesErrors];

export type GetModelInstancesResponses = {
    /**
     * Successfully retrieved list of created model instances
     */
    200: Array<ModelInstance>;
};

export type GetModelInstancesResponse = GetModelInstancesResponses[keyof GetModelInstancesResponses];

export type DeleteModelInstanceData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to delete
         */
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}';
};

export type DeleteModelInstanceErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type DeleteModelInstanceError = DeleteModelInstanceErrors[keyof DeleteModelInstanceErrors];

export type DeleteModelInstanceResponses = {
    /**
     * Model successfully deleted
     */
    200: SuccessResponse;
};

export type DeleteModelInstanceResponse = DeleteModelInstanceResponses[keyof DeleteModelInstanceResponses];

export type GetModelInstanceData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to retrieve information for
         */
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}';
};

export type GetModelInstanceErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type GetModelInstanceError = GetModelInstanceErrors[keyof GetModelInstanceErrors];

export type GetModelInstanceResponses = {
    /**
     * Successfully retrieved model information
     */
    200: ModelInstance;
};

export type GetModelInstanceResponse = GetModelInstanceResponses[keyof GetModelInstanceResponses];

export type GetModelInstanceStateData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to retrieve state for
         */
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/state';
};

export type GetModelInstanceStateErrors = {
    /**
     * Model state cannot be retrieved due to internal error
     */
    400: ErrorResponse;
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type GetModelInstanceStateError = GetModelInstanceStateErrors[keyof GetModelInstanceStateErrors];

export type GetModelInstanceStateResponses = {
    /**
     * Successfully retrieved model state. Each model has its own state, which is a dictionary of arbitrary key-value pairs. Check model-specific documentation for more details.
     */
    200: ModelInstanceState;
};

export type GetModelInstanceStateResponse = GetModelInstanceStateResponses[keyof GetModelInstanceStateResponses];

export type GetModelInstanceParametersData = {
    body?: never;
    path: {
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/parameters';
};

export type GetModelInstanceParametersErrors = {
    /**
     * Model parameters cannot be retrieved due to internal error
     */
    400: ErrorResponse;
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type GetModelInstanceParametersError = GetModelInstanceParametersErrors[keyof GetModelInstanceParametersErrors];

export type GetModelInstanceParametersResponses = {
    /**
     * Successfully retrieved model parameters
     */
    200: ModelInstanceParameters;
};

export type GetModelInstanceParametersResponse = GetModelInstanceParametersResponses[keyof GetModelInstanceParametersResponses];

export type RunInferenceData = {
    body: InferRequest;
    path: {
        /**
         * ID of the model instance to run inference on
         */
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/infer';
};

export type RunInferenceErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type RunInferenceError = RunInferenceErrors[keyof RunInferenceErrors];

export type RunInferenceResponses = {
    /**
     * Successfully ran inference on the model
     */
    200: InferResponse;
};

export type RunInferenceResponse = RunInferenceResponses[keyof RunInferenceResponses];

export type RunLearningData = {
    body: LearnRequest;
    path: {
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/learn';
};

export type RunLearningErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type RunLearningError = RunLearningErrors[keyof RunLearningErrors];

export type RunLearningResponses = {
    /**
     * Successfully ran learning on the model
     */
    200: LearnResponse;
};

export type RunLearningResponse = RunLearningResponses[keyof RunLearningResponses];

export type CreateEpisodeData = {
    body: CreateEpisodeRequest;
    path: {
        /**
         * ID of the model instance to create episode for
         */
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/create-episode';
};

export type CreateEpisodeErrors = {
    /**
     * Episode cannot be created, e.g. it already exists
     */
    400: ErrorResponse;
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model instance not found
     */
    404: NotFoundResponse;
};

export type CreateEpisodeError = CreateEpisodeErrors[keyof CreateEpisodeErrors];

export type CreateEpisodeResponses = {
    /**
     * Successfully created episode
     */
    200: EpisodeInfo;
};

export type CreateEpisodeResponse = CreateEpisodeResponses[keyof CreateEpisodeResponses];

export type GetEpisodesData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to retrieve episodes for
         */
        instance_id: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/episodes';
};

export type GetEpisodesErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model not found
     */
    404: NotFoundResponse;
};

export type GetEpisodesError = GetEpisodesErrors[keyof GetEpisodesErrors];

export type GetEpisodesResponses = {
    /**
     * Successfully retrieved list of episodes
     */
    200: Array<EpisodeInfo>;
};

export type GetEpisodesResponse = GetEpisodesResponses[keyof GetEpisodesResponses];

export type DeleteEpisodeData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to delete episode for
         */
        instance_id: string;
        /**
         * Name of the episode to delete
         */
        episode_name: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/episodes/{episode_name}';
};

export type DeleteEpisodeErrors = {
    /**
     * Episode cannot be deleted, e.g. it is the default episode
     */
    400: ErrorResponse;
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model or episode not found
     */
    404: NotFoundResponse;
};

export type DeleteEpisodeError = DeleteEpisodeErrors[keyof DeleteEpisodeErrors];

export type DeleteEpisodeResponses = {
    /**
     * Successfully deleted episode
     */
    200: SuccessResponse;
};

export type DeleteEpisodeResponse = DeleteEpisodeResponses[keyof DeleteEpisodeResponses];

export type GetEpisodeInfoData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to retrieve episode for
         */
        instance_id: string;
        /**
         * Name of the episode to retrieve
         */
        episode_name: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/episodes/{episode_name}';
};

export type GetEpisodeInfoErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model or episode not found
     */
    404: NotFoundResponse;
};

export type GetEpisodeInfoError = GetEpisodeInfoErrors[keyof GetEpisodeInfoErrors];

export type GetEpisodeInfoResponses = {
    /**
     * Successfully retrieved episode information
     */
    200: EpisodeInfo;
};

export type GetEpisodeInfoResponse = GetEpisodeInfoResponses[keyof GetEpisodeInfoResponses];

export type AttachEventsToEpisodeData = {
    body: AttachEventsToEpisodeRequest;
    path: {
        /**
         * ID of the model instance to attach events to
         */
        instance_id: string;
        /**
         * Name of the episode to attach events to
         */
        episode_name: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/episodes/{episode_name}/attach-events';
};

export type AttachEventsToEpisodeErrors = {
    /**
     * Bad request, e.g. invalid data
     */
    400: ErrorResponse;
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model or episode not found
     */
    404: NotFoundResponse;
};

export type AttachEventsToEpisodeError = AttachEventsToEpisodeErrors[keyof AttachEventsToEpisodeErrors];

export type AttachEventsToEpisodeResponses = {
    /**
     * Successfully attached events to the episode
     */
    200: SuccessResponse;
};

export type AttachEventsToEpisodeResponse = AttachEventsToEpisodeResponses[keyof AttachEventsToEpisodeResponses];

export type WipeEpisodeData = {
    body?: never;
    path: {
        /**
         * ID of the model instance to wipe episode for
         */
        instance_id: string;
        /**
         * Name of the episode to wipe
         */
        episode_name: string;
    };
    query?: never;
    url: '/models/i/{instance_id}/episodes/{episode_name}/wipe';
};

export type WipeEpisodeErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model or episode not found
     */
    404: NotFoundResponse;
};

export type WipeEpisodeError = WipeEpisodeErrors[keyof WipeEpisodeErrors];

export type WipeEpisodeResponses = {
    /**
     * Successfully wiped episode
     */
    200: SuccessResponse;
};

export type WipeEpisodeResponse = WipeEpisodeResponses[keyof WipeEpisodeResponses];

export type AttachMetadataToEventData = {
    body: AttachMetadataToEventRequest;
    path: {
        /**
         * ID of the model instance to attach metadata to
         */
        instance_id: string;
        /**
         * Name of the episode to attach metadata to
         */
        episode_name: string;
        /**
         * ID of the event to attach metadata to
         */
        event_id: number;
    };
    query?: never;
    url: '/models/i/{instance_id}/episodes/{episode_name}/events/{event_id}/attach-metadata';
};

export type AttachMetadataToEventErrors = {
    /**
     * Access token is missing, invalid or has no access to the specific model
     */
    401: UnauthorizedResponse;
    /**
     * Model or episode not found
     */
    404: NotFoundResponse;
};

export type AttachMetadataToEventError = AttachMetadataToEventErrors[keyof AttachMetadataToEventErrors];

export type AttachMetadataToEventResponses = {
    /**
     * Successfully attached metadata to the event
     */
    200: SuccessResponse;
};

export type AttachMetadataToEventResponse = AttachMetadataToEventResponses[keyof AttachMetadataToEventResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:{port}/{basePath}' | 'https://rxinfer.lazydynamics.app/{basePath}' | (string & {});
};