// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zSuccessResponse = z.object({
    message: z.string()
});

export const zErrorResponse = z.object({
    error: z.string(),
    message: z.string().optional()
});

export const zNotFoundResponse = z.object({
    error: z.enum([
        'Not Found'
    ]),
    message: z.string()
});

export const zUnauthorizedResponse = z.object({
    error: z.enum([
        'Unauthorized'
    ]),
    message: z.string()
});

export const zPingResponse = z.object({
    status: z.string().default('ok')
});

export const zServerInfo = z.object({
    rxinfer_version: z.string(),
    server_version: z.string(),
    server_edition: z.string(),
    julia_version: z.string(),
    api_version: z.string().default('v1')
});

export const zTokenGenerateResponse = z.object({
    token: z.string()
});

export const zTokenRolesResponse = z.object({
    roles: z.array(z.string())
});

export const zAvailableModel = z.object({
    details: z.object({
        name: z.string().optional(),
        description: z.string().optional(),
        author: z.string().optional(),
        roles: z.array(z.string()).optional()
    }),
    config: z.object({})
});

export const zCreateModelInstanceRequest = z.object({
    model_name: z.string(),
    arguments: z.object({}).optional(),
    description: z.string().max(128).optional()
});

export const zCreateModelInstanceResponse = z.object({
    instance_id: z.string().uuid()
});

export const zModelInstance = z.object({
    instance_id: z.string().uuid(),
    model_name: z.string(),
    created_at: z.string().datetime(),
    description: z.string(),
    arguments: z.object({}),
    current_episode: z.string()
});

export const zDeleteModelInstanceRequest = z.object({
    instance_id: z.string().uuid()
});

export const zModelInstanceState = z.object({
    state: z.object({})
});

export const zModelInstanceParameters = z.object({
    parameters: z.object({})
});

export const zInferRequest = z.object({
    data: z.object({}),
    timestamp: z.string().datetime().optional(),
    episode_name: z.string().optional().default('default')
});

export const zInferResponse = z.object({
    event_id: z.coerce.bigint(),
    results: z.object({}),
    errors: z.array(zErrorResponse)
});

export const zLearnRequest = z.object({
    episodes: z.array(z.string()).default(['default'])
});

export const zLearnResponse = z.object({
    learned_parameters: z.object({})
});

export const zCreateEpisodeRequest = z.object({
    name: z.string()
});

export const zEpisodeInfo = z.object({
    instance_id: z.string().uuid(),
    episode_name: z.string(),
    created_at: z.string().datetime(),
    events: z.array(z.object({}))
});

export const zAttachEventsToEpisodeRequest = z.object({
    events: z.array(z.object({
        timestamp: z.string().datetime().optional(),
        data: z.object({}).optional(),
        metadata: z.object({}).optional()
    }))
});

export const zAttachMetadataToEventRequest = z.object({
    metadata: z.object({})
});

export const zGetServerInfoResponse = zServerInfo;

export const zPingServerResponse = zPingResponse;

export const zTokenGenerateResponse2 = zTokenGenerateResponse;

export const zTokenRolesResponse2 = zTokenRolesResponse;

export const zGetAvailableModelsResponse = z.array(zAvailableModel);

export const zGetAvailableModelResponse = zAvailableModel;

export const zCreateModelInstanceResponse2 = zCreateModelInstanceResponse;

export const zGetModelInstancesResponse = z.array(zModelInstance);

export const zDeleteModelInstanceResponse = zSuccessResponse;

export const zGetModelInstanceResponse = zModelInstance;

export const zGetModelInstanceStateResponse = zModelInstanceState;

export const zGetModelInstanceParametersResponse = zModelInstanceParameters;

export const zRunInferenceResponse = zInferResponse;

export const zRunLearningResponse = zLearnResponse;

export const zCreateEpisodeResponse = zEpisodeInfo;

export const zGetEpisodesResponse = z.array(zEpisodeInfo);

export const zDeleteEpisodeResponse = zSuccessResponse;

export const zGetEpisodeInfoResponse = zEpisodeInfo;

export const zAttachEventsToEpisodeResponse = zSuccessResponse;

export const zWipeEpisodeResponse = zSuccessResponse;

export const zAttachMetadataToEventResponse = zSuccessResponse;